DEBUG = True

USERNAME = 'wsl'
PASSWORD = '290594'
SERVER = '172.27.48.1'
DB = 'flask_api'

SQLALCHEMY_DATABASE_URI = f'mysql://{USERNAME}:{PASSWORD}@{SERVER}/{DB}'
SQLALCHEMY_TRACK_MODIFICATIONS = True

SECRET_KEY = 'aplicacao-123$'