"""empty message

Revision ID: 431be9748976
Revises: 52311a879f41
Create Date: 2020-03-28 15:37:05.004526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431be9748976'
down_revision = '52311a879f41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tarefa', sa.Column('projeto_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tarefa', 'projeto', ['projeto_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tarefa', type_='foreignkey')
    op.drop_column('tarefa', 'projeto_id')
    # ### end Alembic commands ###
